### ISSUE TITLE
slowsm4: ECB: wrong data pickup and CBC: iv not update after each 16 byte block

### ISSUE THREAD

**Issue by syisunny** [KEDYY/encrypt#1]
in encrypt function, i think it should be

    def encrypt(self, src_data):
        u""" SM4加密
            `src_data`  待加密数据 字节数据，长度如果不是16整数倍，填充\x00
        """
        des_data = ""
        if self.ECB == self.mode:
            for i in segment(src_data, 16):
                des_data += self._crypt(i, self.rk_enc)
        elif self.CBC == self.mode:
            for i in segment(src_data, 16):
                tmp = XOR(i, self.iv)
                tmp = self._crypt(tmp, self.rk_enc)
                self.iv = tmp
                des_data += tmp
        return des_data

**Comment by Yifei0727** [comment]
you are right. but when i wrote this ,  `encrypt` means to use given key and iv (that init params) to encrypt the whole block data `src_data`.
when next time `encrypt` just reuse the key and iv for new src_data.
